name: Deploy frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: Deploy to Alwaysdata
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v5

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Installer les dependances
        run: npm install

      - name: Compiler le Sass
        run: >
          npx sass
          scss/main.scss
          scss/main.css
          --style=compressed
          --no-source-map

      - name: Deployer sur Alwaysdata
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ftp-lequaiantique.alwaysdata.net
          username: lequaiantique
          password: ${{ secrets.ftp_password }}
          protocol: ftps-legacy
          port: 990
          server-dir: /www/
          timeout: 120000
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/*.scss
            **/*.map
